// filepath: /home/artem/loka-frontend/src/app/layout.tsx
import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

// Настройка шрифта Roboto для основного текста
const roboto = Roboto({
  subsets: ["cyrillic", "latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto", // CSS переменная
});

// Настройка шрифта Montserrat для заголовков
const montserrat = Montserrat({
  subsets: ["cyrillic", "latin"],
  weight: ["500", "600", "700"], // Добавлен вес '200'
  variable: "--font-montserrat", // CSS переменная
});

export const metadata: Metadata = {
  title: "Loka",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`${roboto.variable} ${montserrat.variable}`}>
      <body>
        <Header />
        {children}
				<Footer />
      </body>
    </html>
  );
}
